# Generated by Django 2.2.6 on 2020-01-10 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocsBlob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('ipf_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metrics.IPFNumber')),
            ],
        ),
    ]
