# Generated by Django 2.2.6 on 2020-01-10 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_implement_docsblob_model_pt2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docsblob',
            name='ipf_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metrics.IPFNumber', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='docsblob',
            unique_together=set(),
        ),
    ]
