# Generated by Django 2.2.6 on 2020-01-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0004_implement_docsblob_model_pt3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docsblob',
            name='ipf_num',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
